#!/bin/bash
set -e

# prepare exported solution
make assignment.zip

# check if public repo is available
if cd public_repo ; then
    git restore --source=4fdde04756348850bae8f38647dd81a1eba792bf test_assignment
    ./test_assignment ../assignment.zip --force
    cd ..
else
    echo "Reference public repository seems to be missing!"
    echo "Automatically fetch it using './update_public_repo'"
    echo "or manually place it under 'public_repo/' folder."
    exit 1
fi
