#!/bin/bash
set -e

# prepare exported solution
make assignment.zip

# check if public repo is available
if cd public_repo ; then
    git restore --source=461572ff69adfa2ff80209e007a2f49288bad0a3 test_assignment
    ./test_assignment ../assignment.zip --force
    cd ..
else
    echo "Reference public repository seems to be missing!"
    echo "Automatically fetch it using './update_public_repo'"
    echo "or manually place it under 'public_repo/' folder."
    exit 1
fi
