#!/bin/bash

set -e

# remove untracked files from repository
git clean -fd

# reset repository to known state (specified by template hash)
git reset --hard HEAD
git switch --detach `unzip -p "$1" template_hash`

./import_assignment "$1"

# build solution and run tests
./test
